---
- hosts: localhost
  name: loop
  gather_facts: false
  become: false
  tasks:
  
    - name: returning vm list on a folder
      vmware_vm_info:
        validate_certs: no
        hostname: "{{esxi_host.server}}"
        username: "{{ esxi_host.username }}"
        password: "{{ esxi_host.password }}"
        folder: "{{ esxi_host.folder }}"
      register: vms

    - name: Dinamically add VM to hosts file
      become: false
      add_host:
        groups:
          - web-servers
        hostname: "{{item.guest_name}}"
        ansible_host: "{{item.ip_address}}"
        ansible_user: "{{ ansible_ssh_user }}"
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file }}"
        ansible_ssh_pass: "{{ ansible_ssh_pass }}"
      with_items: "{{vms.virtual_machines}}"

    - name: accept new ssh fingerprints
      shell: ssh-keyscan -H {{ item.ip_address }} >> ~/.ssh/known_hosts
      with_items: "{{ vms.virtual_machines }}"
    