---
- hosts: docker-repositories
  gather_facts: false
  tasks:
    - name: Pull Docker Registry image
      community.docker.docker_image:
        name: registry
        source: pull
    
    - name: Start Registry image
      community.docker.docker_container:
        name: "{{ docker.repository.name }}"
        image: "{{ docker.repository.image_name }}"
        published_ports: "{{ '0.0.0.0:' + docker.repository.port | string + ':' + docker.repository.port | string }}"
        state: started
        env:
          REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: "{{ docker.repository.storage_var_path }}"
        restart_policy: always
        volumes: 
          - "{{ docker.repository.storage_var_path + ':/var/lib/registry' }}"