---
- hosts: localhost
  name: loop
  gather_facts: false
  become: false
  tasks:
    - name: iterate vms
      include_tasks: './deploy vm.yaml'
      with_sequence: 0-1
      vars:
        vm: "{{default_vm_config}}"
      loop_control: 
        loop_var: idx




