---
ansible_connection: ssh 
ansible_ssh_user:
ansible_ssh_pass:
ansible_ssh_private_key_file: # Path to the ssh private keys
ssh_key_filename: # name of your private key
public_ssh_key_filename: #name of your public key
snapshot_name: 

esxi_host:
  hostname: localhost.localdomain
  username: root
  password: 
  datacenter: ha-datacenter
  server: 
  port: 443
  folder: '/'

iso_config:
  hostname: demo-server
  username: 
  password:

default_vm_config:
  name:
  hostname: demoserver
  esxi_host: localhost.localdomain
  username:
  password:
  iso_name: ubuntu2004.iso 
  iso_location:
    datastore_name: datastore1
    datastore_path: images
  hardware:
    cpu: 2
    cpu_cores: 2
    memory: 2048
    disk: 
      datastore_name: datastore1
      size: 18
      provision_type: thin
    network:
      port_group: 'VM Network'
      ipv4_address_base: # Please add until the 3rd octet
      dns: 8.8.8.8
      gateway: # Enter the full gateway address
      search_domain: ''